//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ESD.rc
//
#define IDR_MANIFEST                    1
#define IDD_FIRSTPAGE                   9
#define IDD_ABOUTBOX                    100
#define IDD_DLG_LIBMANAGEA              107
#define IDR_MAINFRAME                   128
#define IDR_ESDTYPE                     129
#define ID_FILE_NEW_PROJECT             130
#define ID_FILE_NEW_BLANK               131
#define IDS_INDICATOR_XY                131
#define ID_FILE_OPEN_PROJECT            132
#define IDR_PANE_SOLUTIONEXPLORER       132
#define IDS_INDICATOR_UNIT              132
#define IDS_INDICATOR_ORTHO             133
#define IDR_TOOLBAR_FULLSCREEN          134
#define IDR_POPUP_PANES                 134
#define IDS_INDICATOR_CURSOR            134
#define IDS_INDICATOR_INFO              135
#define ID_EDIT_FINDANDREPLACE          136
#define IDS_INDICATOR_SNAP              136
#define IDR_TOOLBAR_THEME               137
#define ID_FINDANDREPLACE_FIND          138
#define IDR_DYNAMIC_HELP                138
#define IDS_INDICATOR_VISIBLE           138
#define ID_FINDANDREPLACE_REPLACE       139
#define IDS_INDICATOR_ELECTRICAL        139
#define ID_FINDANDREPLACE_FINDINFILES   140
#define ID_INDICATOR_CURSOR             140
#define ID_VIEW_OPEN                    141
#define IDR_SCH_MAINMENU                142
#define ID_Menu147                      147
#define ID_VIEW_WEBBROWSER              148
#define IDI_POPUP_CLOSE                 148
#define ID_WEBBROWSER_HOME              149
#define ID_WEBBROWSER_SEARCH            150
#define ID_WEBBROWSER_BACK              151
#define IDR_TO_PCB                      151
#define ID_WEBBROWSER_FORWARD           152
#define ID_VIEW_TOOLBARS                153
#define ID_VIEW_FULLSCREEN              154
#define IDR_TOOLBAR_SCH_MAIN            154
#define ID_VIEW_TOOLBARS155             155
#define ID_PROJECT_ADDRESOURCE          156
#define IDR_TOOLBAR_PCB_MAIN            156
#define ID_PROJECT_ADDNEWITEM           157
#define ID_PROJECT_ADDEXISTINGITEM      158
#define IDR_TOOLBAR_SCH_WINDOW          158
#define ID_PROJECT_NEWFOLDER            159
#define ID_BUILD_BUILDSOLUTION          160
#define IDR_TOOLBAR_PCB_WINDOW          160
#define ID_BUILD_REBUILDSOLUTION        161
#define ID_BUILD_CLEANSOLUTION          162
#define IDB_FILETREE                    162
#define ID_BUILD_COMPILE                163
#define ID_DEBUG_WINDOWS                164
#define IDB_CLASSTREE                   164
#define IDB_RESTREE                     165
#define IDD_SCH_SHEET_OPTIONS           166
#define ID_DEBUG_STARTWITHOUTDEBUG      167
#define IDD_SCH_SHEET_UNITS             167
#define ID_DEBUG_PROSSESES              168
#define ID_DEBUG_EXCEPTIONS             169
#define ID_DEBUG_STEPINTO               170
#define ID_DEBUG_STEPOVER               171
#define ID_TOOLS_OPTIONS                172
#define ID_HELP_CONTENTS                174
#define IDD_EDIT_COMPONENT              174
#define ID_HELP_INDEX175                175
#define IDD_EDIT_PIN                    175
#define ID_HELP_SEARCH                  176
#define IDR_TOOLBAR_EXT                 177
#define IDR_PCB_MAINMEN                 177
#define IDR_PCB_MAINMENU                177
#define IDD_EDIT_POLYLINE               177
#define IDD_VERTICES                    178
#define ID_FILE_OPENSOLUTION            179
#define IDD_EDIT_POLYGON                179
#define ID_FILE_CLOSESOLUTION           180
#define IDD_EDIT_ELLIPSEFILL            180
#define ID_DEBUG_START                  181
#define IDD_EDIT_PIE                    181
#define ID_PROJECT_ADDCLASS             182
#define IDD_EDIT_ROUNDRECT              182
#define IDD_EDIT_ELLIPSE                183
#define IDD_EDIT_ARC                    184
#define IDD_EDIT_RECT                   185
#define IDD_EDIT_SHEETSYMBOL            186
#define ID_Menu                         187
#define IDD_EDIT_SHEETENTRY             187
#define IDB_BITMAP_PANEICONS            188
#define IDB_ABOUTDLG                    188
#define IDD_EDIT_OFFSHEET               188
#define IDR_TOOLBAR_WEB                 189
#define IDD_EDIT_POWER                  189
#define ID_WEBBROWSER_STOP              190
#define IDD_EDIT_PORT                   190
#define ID_WEBBROWSER_REFRESH           191
#define IDD_EDIT_LABEL                  191
#define IDD_EDIT_NETLABEL               191
#define ID_WEBBROWSER_FAVORITES         192
#define IDD_EDIT_BUS                    192
#define ID_WEBBROWSER_ORGANIZE          193
#define IDD_EDIT_WIRE                   193
#define ID_BUTTON32806                  194
#define IDD_EDIT_TEXTFRAME              194
#define ID_WEBBROWSER_FONT              195
#define IDD_EDIT_JUNCTION               195
#define ID_WEBBROWSER_SYNC              196
#define IDD_EDIT_BUSENTRY               196
#define ID_WEBBROWSER_PREV              197
#define IDD_EDIT_IEEE                   197
#define ID_WEBBROWSER_NEXT              198
#define IDD_EDIT_TEXT                   198
#define IDD_EDIT_BEZIER                 199
#define ID_VIEW_SOLUTIONEXPLORER        200
#define IDD_EDIT_GRAPHIC                200
#define ID_VIEW_CLASSVIEW               201
#define IDB_TOOLBOXICONS                201
#define ID_VIEW_RESOURCEVIEW            202
#define ID_VIEW_PROPERTIESWINDOW        203
#define ID_VIEW_TOOLBOX                 204
#define ID_WINDOWS_OUTPUT               205
#define ID_HELP_DYNAMICHELP             206
#define IDB_EDIT_POLYLINE               207
#define IDB_EDIT_ARC                    217
#define IDB_EDIT_POLYGON                218
#define IDB_EDIT_ELLIPSEFILL            219
#define IDB_EDIT_PIE                    220
#define IDB_EDIT_ROUNDRECT              221
#define IDB_EDIT_ELLIPSE                222
#define IDB_EDIT_RECT                   223
#define IDB_EDIT_SHEETSYMBOL            224
#define IDB_EDIT_SHEETENTRY             225
#define IDB_EDIT_OFFSHEET               226
#define IDB_EDIT_POWER                  227
#define IDB_EDIT_PORT                   228
#define IDB_EDIT_NETLABEL               229
#define IDB_EDIT_BUS                    230
#define IDB_EDIT_BUSENTRY               231
#define IDB_EDIT_WIRE                   232
#define IDB_EDIT_TEXTFRAME              233
#define IDB_EDIT_JUNCTION               234
#define IDB_EDIT_TEXT                   235
#define IDB_EDIT_BEZIER                 236
#define IDB_EDIT_GRAPHIC                237
#define IDR_MENU_MULTI_SELECTION        239
#define IDR_MULTI_SELECTION             239
#define ID_CLASSVIEW_OUTPUT             251
#define IDB_GFX1                        254
#define IDB_GFX2                        256
#define IDD_EDIT_SHEETSYMBOL_DF         262
#define IDD_EDIT_COMPTEXT               264
#define IDD_FONT                        268
#define IDD_SELECT_PIN                  270
#define IDD_TEXTFRAME_TEXT              271
#define IDD_REPORT_ELEMENTS             272
#define IDD_MESSAGE_OPENFILE            275
#define IDR_TOOLBAR1                    278
#define IDD_PRINT_SETUP_SCH             280
#define IDB_PRINT_PORTRAIT              282
#define IDB_PRINT_LANDSCAPE             283
#define IDB_PRINT_S01                   285
#define IDB_PRINT_WINDOW                286
#define IDB_PRINT_SHEET                 287
#define IDD_INPUT_TEXT                  288
#define IDC_HANDZOOM                    290
#define IDC_PICKUP                      291
#define IDC_SELECTIONMOVE               292
#define IDD_PLACE_COMP                  293
#define IDD_SCHLIB_BROWSE               294
#define IDD_PCBLIB_BROWSE               295
#define IDD_PLACE_PACKAGE               296
#define IDD_SCHLIB_SOURCE_COMP          298
#define IDD_SCHLIB_ATTRIB               299
#define IDB_STARTPAGE                   300
#define ID_TOOLBOXFOLDER_PROPERTYPANES  300
#define IDD_SCHLIB_LIST                 300
#define ID_TOOLBOXFOLDER_DATA           301
#define IDD_SCHLIB_ADD                  301
#define ID_TOOLBOXFOLDER_COMPONENTS     302
#define IDD_SCHLIB_NEW                  302
#define ID_TOOLBOXFOLDER_WINDOWSFORMS   303
#define ID_TOOLBOXFOLDER_CLIPBOARDRING  304
#define IDD_EDIT_FINDTEXT               304
#define ID_TOOLBOXFOLDER_GENERAL        305
#define IDD_EDIT_REPLACETEXT            306
#define IDD_EDIT_JUMP_LOCATION          307
#define IDD_EDIT_JUMP_COMPONENT         308
#define IDR_PNG1                        310
#define IDC_CURSOR1                     311
#define IDC_SELECTIONCOPY               311
#define IDC_PCB_SELECTIONCOPY           312
#define IDR_MENU1                       314
#define IDR_FAST_ZOOM                   318
#define IDR_ZOOM                        318
#define IDD_EDIT_REPEAT                 319
#define IDD_PERFERENCE                  324
#define IDD_ANNOTATE_RESET              326
#define IDD_ANNOTATE                    327
#define IDB_ANNOTATE_TBLR               329
#define IDB_ANNOTATE_BTLR               330
#define IDB_ANNOTATE_LRTB               331
#define IDB_ANNOTATE_LRBT               332
#define IDD_HIGHLIGHT_LIST              336
#define IDD_DIALOG2                     337
#define IDD_REPORT                      337
#define IDD_PCB_MULTI_SELECTION         338
#define IDD_PCB_EDIT_ARC                339
#define IDB_PCB_EDIT_ARC                340
#define IDD_PCB_BOARD_OPTIONS           341
#define IDB_PCB_EDIT_TRACK              343
#define IDB_PCB_EDIT_VIA                344
#define IDD_PCB_EDIT_TRACK              345
#define IDD_PCB_EDIT_VIA                346
#define IDB_PCB_EDIT_TEXT               347
#define IDD_PCB_EDIT_TEXT               348
#define IDB_PCB_EDIT_FILL               350
#define IDB_PCB_EDIT_DIMENSION          351
#define IDB_PCB_EDIT_COORDINATE         352
#define IDD_PCB_EDIT_FILL               353
#define IDD_PCB_EDIT_DIMENSION          354
#define IDD_PCB_EDIT_COORDINATE         355
#define IDD_PCB_EDIT_PAD                357
#define IDD_PCB_EDIT_COMP               358
#define IDD_PCB_LAYER_STACK             359
#define IDB_PCB_SEL1                    361
#define IDB_PCB_SEL2                    362
#define IDB_PCB_SEL3                    363
#define IDB_PCB_SEL4                    364
#define IDB_PCB_SEL5                    365
#define IDB_PCB_SEL6                    366
#define IDB_PCB_SEL7                    367
#define IDB_PCB_SEL8                    368
#define IDD_PCB_LAYER_SETUP             369
#define IDB_PCB_SEL9                    370
#define IDD_PCB_EDIT_REGION             371
#define IDB_PCB_EDIT_REGION             372
#define IDR_STATUSMENU                  376
#define IDD_PCB_LAYERNAME               377
#define IDD_PCB_POWERPLANE              378
#define IDD_PCB_SNAPSETUP               379
#define IDD_PCB_EDIT_SPLITPLANE         382
#define IDD_PCB_EDIT_POLYGON            383
#define IDB_PCB_EDIT_POLYGON1_1         384
#define IDB_PCB_EDIT_POLYGON1_2         385
#define IDB_PCB_EDIT_POLYGON1_3         386
#define IDB_PCB_EDIT_POLYGON1_4         387
#define IDB_PCB_EDIT_POLYGON2           388
#define IDB_PCB_EDIT_POLYGON3           389
#define IDD_PCB_EDIT_DIMENSION_LINEAR   392
#define IDB_PCB_EDIT_DIMENSION_LINEAR   393
#define IDD_PRINT_SETUP_PCB             397
#define IDB_PRINT_BOARD                 399
#define ID_TOOLBOXITEM_POINTER          400
#define ID_TOOLBOXITEM_BUTTON           401
#define IDD_PCB_LAYER_SET               401
#define ID_TOOLBOXITEM_CHECK_BOX        402
#define IDD_PCB_BOARD_INFO              402
#define ID_TOOLBOXITEM_EDIT_CONTROL     403
#define IDD_PCB_NET_EDIT                403
#define ID_TOOLBOXITEM_COMBO_BOX        404
#define IDD_PCB_NET_PARAM_EDIT          404
#define ID_TOOLBOXITEM_LIST_BOX         405
#define IDB_PCB_EDIT_NET                405
#define ID_TOOLBOXITEM_GROUP_BOX        406
#define IDR_MAKELIB                     406
#define ID_TOOLBOXITEM_RADIO_BUTTON     407
#define ID_TOOLBOXITEM_STATIC_TEXT      408
#define ID_TOOLBOXITEM_PICTURE_CONTROL  409
#define ID_TOOLBOXITEM_HORIZONTAL_SCROLL_BAR 410
#define ID_TOOLBOXITEM_VERTICAL_SCROLL_BAR 411
#define ID_TOOLBOXITEM_SLIDER_CONTROL   412
#define ID_TOOLBOXITEM_SPIN_CONTROL     413
#define ID_TOOLBOXITEM_PROGRESS_CONTROL 414
#define ID_TOOLBOXITEM_HOT_KEY          415
#define ID_TOOLBOXITEM_LIST_CONTROL     416
#define ID_TOOLBOXITEM_TREE_CONTROL     417
#define ID_TOOLBOXITEM_TAB_CONTROL      418
#define ID_TOOLBOXITEM_ANIMATION_CONTROL 419
#define ID_TOOLBOXITEM_RICH_EDIT_CONTROL 420
#define ID_TOOLBOXITEM_DATE_TIME_PICKER 421
#define ID_TOOLBOXITEM_MONTH_CALENDAR_CONTROL 422
#define ID_TOOLBOXITEM_IP_ADDRESS_CONTROL 423
#define ID_TOOLBOXITEM_EXTENDED_COMBO_BOX 424
#define ID_TOOLBOXITEM_CUSTOM_CONTROL   425
#define ID_TOOLBOXITEM_DATASET          426
#define ID_TOOLBOXITEM_OLEDBDATAADAPTER 427
#define ID_TOOLBOXITEM_OLEDBCONNECTION  428
#define ID_TOOLBOXITEM_OLEDBCOMMAND     429
#define ID_TOOLBOXITEM_SQLDATAADAPTER   430
#define ID_TOOLBOXITEM_SQLCONNECTION    431
#define ID_TOOLBOXITEM_SQLCOMMAND       432
#define ID_TOOLBOXITEM_DATAVIEW         433
#define ID_TOOLBOXITEM_FILESYSTEMWATCHER 434
#define ID_TOOLBOXITEM_EVENTLOG         435
#define ID_TOOLBOXITEM_DIRECTORYENTRY   436
#define ID_TOOLBOXITEM_DIRECTORYSEARCHER 437
#define ID_TOOLBOXITEM_MESSAGEQUEUE     438
#define ID_TOOLBOXITEM_PERFORMANCECOUNTER 439
#define ID_TOOLBOXITEM_PROCESS          440
#define ID_TOOLBOXITEM_SERVICECONTROLLER 441
#define ID_TOOLBOXITEM_TIMER            442
#define IDR_SCH_A                       451
#define IDR_SCH_B                       452
#define IDR_SCH_C                       453
#define IDR_SCH_D                       454
#define IDR_SCH_E                       455
#define IDR_SCH_F                       456
#define IDR_SCH_G                       457
#define IDR_SCH_H                       458
#define IDR_SCH_I                       459
#define IDR_SCH_J                       460
#define IDR_SCH_K                       461
#define IDR_SCH_L                       462
#define IDR_SCH_M                       463
#define IDR_SCH_N                       464
#define IDR_SCH_O                       465
#define IDR_SCH_P                       466
#define IDR_SCH_Q                       467
#define IDR_SCH_S                       469
#define IDR_SCH_T                       470
#define IDR_SCH_U                       471
#define IDR_SCH_V                       472
#define IDR_SCH_W                       473
#define IDR_SCH_X                       474
#define IDR_SCH_Y                       475
#define IDR_SCH_Z                       476
#define IDD_MY_HELP                     477
#define IDD_REPORT_COMPNET              478
#define IDB_HELP                        479
#define IDB_FIRSTPAGE                   480
#define IDR_PCB_A                       481
#define IDR_PCB_B                       482
#define IDR_PCB_C                       483
#define IDR_PCB_D                       484
#define IDR_PCB_E                       485
#define IDR_PCB_F                       486
#define IDR_PCB_G                       487
#define IDR_PCB_H                       488
#define IDR_PCB_I                       489
#define IDR_PCB_J                       490
#define IDR_PCB_K                       491
#define IDR_PCB_L                       492
#define IDR_PCB_M                       493
#define IDR_PCB_N                       494
#define IDR_PCB_O                       495
#define IDR_PCB_P                       496
#define IDR_PCB_Q                       497
#define IDR_PCB_S                       499
#define IDR_PCB_T                       500
#define IDR_PCB_U                       501
#define IDR_PCB_V                       502
#define IDR_PCB_W                       503
#define IDR_PCB_X                       504
#define IDR_PCB_Y                       505
#define IDR_PCB_Z                       506
#define IDD_MISSING_COMPONENT           507
#define IDD_PCB_LOAD_PACKAGE_XY         508
#define IDD_PCB_LOAD_PACKAGE_BYNAME     509
#define IDD_PCB_HIGHLIGH_PINS           510
#define IDD_PCB_JUMP_COMP               511
#define IDD_PCB_RULES1                  512
#define IDD_PCB_RULES2                  513
#define IDD_PCB_RULES3                  514
#define IDD_PCB_RULES4                  515
#define IDD_PCB_RULES5                  516
#define IDD_PCB_RULES6                  517
#define IDD_PCB_RULES7                  518
#define IDB_PCB_RULES_CLEARANCE         520
#define IDB_PCB_RULES_WIDTH             521
#define IDB_PCB_RULES_VIA               522
#define IDB_PCB_RULES_CORNER1           523
#define IDB_PCB_RULES_CORNER2           524
#define IDB_PCB_RULES_CORNER3           525
#define IDD_PCB_RULES_PRIORITY_SETUP    526
#define IDB_PCB_RULES_SOLDER            528
#define IDB_PCB_RULES_PASTE             529
#define IDB_PCB_RULES_INTERNAL1         530
#define IDB_PCB_RULES_INTERNAL2         531
#define IDB_PCB_RULES_INTERNAL3         532
#define IDB_PCB_RULES_POLYGON1          537
#define IDB_PCB_RULES_POLYGON2          538
#define IDR_MENU2                       539
#define IDD_DIALOG1                     542
#define IDD_PCB_NETNAME                 542
#define IDD_PCBLIB_ATTRIB               543
#define IDD_PCBLIB_ADD                  544
#define IDD_PCB_TEARDROP                545
#define IDD_PCB_PERFERENCE              546
#define IDI_ICON1                       550
#define IDI_ICON2                       551
#define IDD_GLOBAL_BUS                  552
#define IDD_GLOBAL_TEXT                 553
#define IDD_GLOBAL_DESIGNATOR           554
#define IDD_GLOBAL_FILL                 555
#define IDD_GLOBAL_POWER                556
#define IDD_GLOBAL_POLYLINE             557
#define IDD_GLOBAL_PORT                 558
#define IDD_LIB_MANAGER_A               559
#define IDR_PANE_PROPERTIES             600
#define ID_THEME_SKINFRAMEWORK          620
#define IDC_IPEDIT                      804
#define IDR_MAINTOOLBAR                 900
#define IDR_PLACETOOLBAR1               901
#define IDR_PLACETOOLBAR2               902
#define IDR_OTHERTOOLBAR1               903
#define IDR_OTHERTOOLBAR2               904
#define IDR_PCB_MAINTOOLBAR             905
#define IDR_PCB_PLACETOOLBAR            906
#define IDR_PCB_DESIGNTOOLBAR           907
#define IDR_PCB_OTHERTOOLBAR1           908
#define IDR_PCB_OTHERTOOLBAR2           909
#define IDC_STATIC_RED1                 1001
#define IDC_STATIC_RED2                 1002
#define IDC_STATIC_SETUP1               1008
#define IDC_STATIC_SETUP2               1009
#define IDC_STATIC_SETUP3               1010
#define IDC_STATIC_SETUP4               1011
#define IDC_STATIC_SETUP5               1012
#define IDC_TXT_URL                     1013
#define IDC_TXT_EMAIL                   1014
#define IDC_TXT_URL3                    1014
#define IDC_TXT_EMAIL2                  1015
#define IDC_USER                        1016
#define IDC_UNIT                        1017
#define IDC_SN                          1018
#define IDC_CHECK_TITLE                 1019
#define IDC_COMBO_ORIENTATION           1020
#define IDC_CHECK_REFERENCE             1021
#define IDC_CHECK_SHOWBORDER            1022
#define IDC_COMBO_STANDARD              1023
#define IDC_CHECK_SNAP                  1024
#define IDC_CHECK_VISIBLE               1025
#define IDC_EDIT_SNAP                   1026
#define IDC_EDIT_VISIBLE                1027
#define IDC_CHECK_ELECTRICAL            1028
#define IDC_EDIT_ELECTRICAL             1029
#define IDC_BUTTON_SYSTEMFONT           1030
#define IDC_CHECK_CUSTOM                1031
#define IDC_EDIT_CUSTOMWIDTH            1032
#define IDC_EDIT_CUSTOMHEIGHT           1033
#define IDC_EDIT_XCOUNT                 1034
#define IDC_EDIT_YCOUNT                 1035
#define IDC_EDIT_MARGIN                 1036
#define IDC_BUTTON_UPDATE               1037
#define IDC_COMBO_SHEETNUM              1038
#define IDC_EDIT_SHEETNAME              1039
#define IDC_COMBO_TITLE                 1040
#define IDC_EDIT_NUMBERSPACE            1041
#define IDC_CHECK_I                     1043
#define IDC_CHECK_M                     1044
#define IDC_COMBO_I                     1045
#define IDC_COMBO_M                     1046
#define IDC_STATIC_UNIT                 1047
#define IDC_CHECK_SHEETENABLE           1048
#define IDC_BUTTON_ALLON                1049
#define IDC_BUTTON_USEDON               1050
#define IDC_STATIC_BORDERCOLOR          1055
#define IDC_STATIC_SHEETCOLOR           1057
#define IDC_BUTTON_BORDERCOLOR_DEFAULT  1058
#define IDC_BUTTON_SHEETCOLOR_DEFAULT   1059
#define IDC_STATIC_SUBCAPTION1          1059
#define IDC_STATIC_SUBCAPTION2          1060
#define IDC_STATIC_SUBCAPTION3          1061
#define IDC_STATIC_SUBCAPTION4          1062
#define IDC_STATIC_SUBCAPTION5          1063
#define IDC_STATIC_SUBCAPTION2_1        1064
#define IDC_STATIC_SUBCAPTION2_2        1065
#define IDC_STATIC_SUBCAPTION2_3        1066
#define IDC_STATIC_SUBCAPTION2_4        1067
#define IDC_STATIC_SUBCAPTION2_5        1068
#define IDC_STATIC_SUBCAPTION3_1        1069
#define IDC_STATIC_SUBCAPTION3_2        1070
#define IDC_STATIC_SUBCAPTION3_3        1071
#define IDC_STATIC_SUBCAPTION3_4        1072
#define IDC_STATIC_SUBCAPTION3_5        1073
#define IDC_STATIC_SUBCAPTION4_1        1074
#define IDC_STATIC_SUBCAPTION4_2        1075
#define IDC_STATIC_SUBCAPTION4_3        1076
#define IDC_STATIC_SUBCAPTION4_4        1077
#define IDC_STATIC_SUBCAPTION4_5        1078
#define IDC_BUTTON_EDITPINS             1079
#define IDC_EDIT_DESIGNATOR             1080
#define IDC_CHECK_DESIGNATOR_VISIBLE    1081
#define IDC_CHECK_DESIGNATOR_LOCKED     1082
#define IDC_COMBO_COMMENT               1083
#define IDC_CHECK_COMMENT_VISIBLE       1084
#define IDC_BUTTON_BACKWORD             1085
#define IDC_BUTTON_PREV                 1086
#define IDC_BUTTON_NEXT                 1088
#define IDC_BUTTON_FORWORD              1089
#define IDC_STATIC_PARTNUM              1090
#define IDC_CHECK_PART_LOCKED           1091
#define IDC_EDIT_DESCRIPTION            1092
#define IDC_EDIT_UNIQUE_ID              1093
#define IDC_COMBO2                      1096
#define IDC_COMBO_ANCHOR1               1096
#define IDC_FONT_SIZE                   1096
#define IDC_COMBO_SCALEMODE             1096
#define IDC_COMBO_PART                  1096
#define IDC_COMBO_GRIDTYPE              1096
#define IDC_COMBO_SNAP_X                1096
#define IDC_COMBO_FONT                  1096
#define IDC_COMBO_SHAPE_TOP             1096
#define IDC_COMBO                       1096
#define IDC_EDIT5                       1097
#define IDC_COMBO_ENDSHAPE              1097
#define IDC_COMBO_ANCHOR2               1097
#define IDC_EDIT_LIBRARY                1097
#define IDC_EDIT_PINLENGTH              1097
#define IDC_EDIT_POWERGROUND            1097
#define IDC_COMBO_SNAP_Y                1097
#define IDC_EDIT_INVERT                 1097
#define IDC_EDIT_XSIZE_TOP              1097
#define IDC_EDIT_REMOVE_NECK            1097
#define IDC_EDIT_LOCATION_X             1098
#define IDC_COMBO_INSIDE_EDGE           1098
#define IDC_COMBO_SIZE                  1098
#define IDC_EDIT_SIGNALGROUND           1098
#define IDC_COMBO_COMP_X                1098
#define IDC_EDIT_YSIZE_TOP              1098
#define IDC_COMBO_C_FONT                1098
#define IDC_EDIT_LOCATION_Y             1099
#define IDC_COMBO_OUTSIDE_EDGE          1099
#define IDC_EDIT_EARTH                  1099
#define IDC_COMBO_COMP_Y                1099
#define IDC_EDIT_XSIZE_MID              1099
#define IDC_EDIT_C_INVERT               1099
#define IDC_COMBO3                      1100
#define IDC_COMBO_OUTSIDE               1100
#define IDC_EDIT_SIZE                   1100
#define IDC_COMBO_SHEETSIZE             1100
#define IDC_COMBO_EGRID_RANGE           1100
#define IDC_EDIT_YSIZE_MID              1100
#define IDC_COMBO4                      1101
#define IDC_EDIT_ORIENTATION            1101
#define IDC_COMBO_MODE                  1101
#define IDC_COMBO_VGRID_STYLE           1101
#define IDC_COMBO_SHAPE_MID             1101
#define IDC_CHECK_MIRRORED              1102
#define IDC_COMBO_VGRID1                1102
#define IDC_EDIT_XSIZE_BOTTOM           1102
#define IDC_CHECK_LOCKPINS              1103
#define IDC_COMBO_VGRID2                1103
#define IDC_EDIT_YSIZE_BOTTOM           1103
#define IDC_CHECK_SHOW_ALLPINS          1104
#define IDC_EDIT_SHAPE_BOTTOM           1104
#define IDC_COMBO_SHAPE_BOTTOM          1104
#define IDC_CHECK_LOCAL_COLORS          1105
#define IDC_STATIC_FILLCOLOR            1106
#define IDC_EDIT_PINNAME                1107
#define IDC_STATIC_BORDERCOLOROLOR      1107
#define IDC_STATIC_TEXTCOLOR            1107
#define IDC_STATIC_LINECOLOR            1108
#define IDC_EDIT_PINNUMBER              1108
#define IDC_STATIC_PINCOLOR             1109
#define IDC_COMBO_ELECTRICAL_TYPE       1109
#define IDC_EDITDESCRIPTION             1110
#define IDC_CHECK_HIDE                  1111
#define IDC_EDIT_CONNECT_TO             1112
#define IDC_CHECK_PINNAME_VISIBLE       1113
#define IDC_CHECK_PINNUMBER_VISIBLE     1114
#define IDC_EDIT_PIN_LOCATION_X         1115
#define IDC_EDIT_PIN_LOCATION_Y         1116
#define IDC_EDIT_PIN_LENGTH             1117
#define IDC_COMBO_PIN_ORIENTATION       1118
#define IDC_STATIC_COLOR                1119
#define IDC_COMBO_INSIDE                1120
#define IDC_EDIT_PARTNUM                1121
#define IDC_COMBO_LINEWIDTH             1122
#define IDC_COMBO_LINESTYLE             1123
#define IDC_EDIT_LOCATION_Y1            1124
#define IDC_EDIT_LOCATION_X1            1125
#define IDC_EDIT_LOCATION_Y2            1126
#define IDC_COMBO_STARTSHAPE            1126
#define IDC_EDIT_LOCATION_X2            1127
#define IDC_LIST_VERTICES               1128
#define IDC_CHECK_DRAWSOLID             1129
#define IDC_CHECK_TRANSPARENT           1130
#define IDC_COMBO_BORDERWIDTH           1131
#define IDC_EDIT_RADIUS_Y               1134
#define IDC_EDIT_RADIUS_X               1135
#define IDC_EDIT_STARTANGLE             1141
#define IDC_EDIT_ENDANGLE               1142
#define IDC_EDIT_RADIUS                 1143
#define IDC_CHECK_AUTOPOSITION          1155
#define IDC_CHECK_NAMELOCKED            1156
#define IDC_CHECK_NAMEVISIBLE           1157
#define IDC_CHECK_TEXTLOCKED            1158
#define IDC_CHECK_TEXTVISIBLE           1159
#define IDC_EDIT_SIZE_Y                 1160
#define IDC_EDIT_SIZE_X                 1161
#define IDC_EDIT_NAME                   1163
#define IDC_EDIT_POSITION               1164
#define IDC_EDIT_TYPE                   1164
#define IDC_COMBO_TYPE                  1165
#define IDC_COMBO_SIDE                  1166
#define IDC_COMBO_STYLE                 1167
#define IDC_EDIT_NET                    1168
#define IDC_COMBO_TEXT_POSITION         1168
#define IDC_COMBO_ARROW_POSITION        1169
#define IDC_CHECK_SHOW_NETNAME          1172
#define IDC_COMBO_ALIGNMENT             1176
#define IDC_EDIT_LENGTH                 1178
#define IDC_BUTTON_FONT                 1181
#define IDC_COMBO_WIDTH                 1182
#define IDC_BUTTON_TEXT                 1184
#define IDC_CHECK_WORDWRAP              1185
#define IDC_CHECK_CLIP                  1186
#define IDC_EDIT1                       1195
#define IDC_EDIT_LOCATIONX              1195
#define IDC_EDIT_FILENAME               1195
#define IDC_EDIT_TEXT                   1195
#define IDC_EDIT_DF                     1195
#define IDC_EDIT_UNIQUEID               1195
#define IDC_EDIT_PACKAGE                1195
#define IDC_EDIT_SCALE                  1195
#define IDC_EDIT_COMP_PREFIX            1195
#define IDC_EDIT_SEARCH                 1195
#define IDC_EDIT_LIBNAME                1195
#define IDC_EDIT_PINNUM                 1195
#define IDC_EDIT_NUMBER                 1195
#define IDC_EDIT_I1                     1195
#define IDC_EDIT_STARTNUM               1195
#define IDC_EDIT_LIST                   1195
#define IDC_EDIT_SANGLE                 1195
#define IDC_EDIT_SHEET_X                1195
#define IDC_EDIT_HOLEDIA                1195
#define IDC_EDIT_HEIGHT                 1195
#define IDC_EDIT_PAD_X                  1195
#define IDC_EDIT_LAYERNAME              1195
#define IDC_EDIT_TRACK_WIDTH            1195
#define IDC_EDIT_TEXT_LINEWIDTH         1195
#define IDC_EDIT_START_X                1195
#define IDC_EDIT_TEXT_GAP               1195
#define IDC_EDIT_VIAHOLE                1195
#define IDC_COMBO_JUNCTIONSIZE          1196
#define IDC_EDIT_COMP_COMMENT           1196
#define IDC_EDIT_REPLACETEXT            1196
#define IDC_EDIT_NDELTA                 1196
#define IDC_EDIT_I2                     1196
#define IDC_EDIT_EANGLE                 1196
#define IDC_EDIT_SHEET_Y                1196
#define IDC_EDIT_DIA                    1196
#define IDC_EDIT_PAD_Y                  1196
#define IDC_EDIT13                      1196
#define IDC_EDIT_GRID_SIZE              1196
#define IDC_EDIT_PULLBACK               1196
#define IDC_EDIT_TEXT_HEIGHT            1196
#define IDC_EDIT_START_Y                1196
#define IDC_EDIT_VIA                    1196
#define IDC_EDIT_VIASIZE                1196
#define IDC_EDIT_REF                    1197
#define IDC_EDIT_XDELTA                 1197
#define IDC_EDIT_I3                     1197
#define IDC_EDIT_SHEET_WIDTH            1197
#define IDC_EDIT_ROTATION               1197
#define IDC_EDIT_PAD_ROTATION           1197
#define IDC_EDIT8                       1197
#define IDC_EDIT_ID_HEIGHT              1197
#define IDC_EDIT_TEXT_WIDTH             1197
#define IDC_COMBO_SYMBOL                1198
#define IDC_EDIT_YDELTA                 1198
#define IDC_EDIT_M1                     1198
#define IDC_EDIT_SHEET_HEIGHT           1198
#define IDC_EDIT_HOLESIZE               1198
#define IDC_EDIT9                       1198
#define IDC_EDIT_ID_WIDTH               1198
#define IDC_EDIT_ANGLE                  1198
#define IDC_COMBO_TEXT                  1199
#define IDC_EDIT_M2                     1199
#define IDC_EDIT10                      1199
#define IDC_EDIT_ID_ROTATION            1199
#define IDC_EDIT_END_X                  1199
#define IDC_EDIT_M3                     1200
#define IDC_EDIT11                      1200
#define IDC_EDIT_ID_X                   1200
#define IDC_EDIT_END_Y                  1200
#define IDC_EDIT_LINE_WIDTH             1200
#define IDC_COMBO_H_JUST                1201
#define IDC_EDIT12                      1201
#define IDC_EDIT_ID_Y                   1201
#define IDC_EDIT_ARROW_LENGTH           1201
#define IDC_COMBO_V_JUST                1202
#define IDC_EDIT_C_HEIGHT               1202
#define IDC_EDIT_ARROWWIDTH             1202
#define IDC_BUTTON_BROWSE               1203
#define IDC_EDIT_C_WIDTH                1203
#define IDC_EDIT_OFFSET                 1203
#define IDC_CHECK_EMBEDDED              1204
#define IDC_EDIT_C_ROTATION             1204
#define IDC_EDIT_EXTWIDTH               1204
#define IDC_EDIT_C_X                    1205
#define IDC_EDIT_GAP                    1205
#define IDC_CHECK_RATIO                 1206
#define IDC_EDIT_C_Y                    1206
#define IDC_EDIT_COMP_ROTATION          1207
#define IDC_EDIT_COMP_X                 1208
#define IDC_STATIC_BITMAP               1209
#define IDC_STATIC_BITMAP_POLYLINE      1209
#define IDC_STATIC_EDIT_VIA             1209
#define IDC_EDIT_COMP_Y                 1209
#define IDC_BUTTON_ADD                  1210
#define IDC_BUTTON_REMOVE               1211
#define IDC_EDIT_LIB                    1211
#define IDC_STATIC_ARC                  1212
#define IDC_STATIC_COMPNUM              1212
#define IDC_STATIC_BITMAP_ARC           1213
#define IDC_STATIC_EDIT_ARC             1213
#define IDC_STATIC_TRACK                1213
#define IDC_STATIC_WIRENUM              1214
#define IDC_STATIC_VIA                  1214
#define IDC_STATIC_EDIT_ELLIPSE         1215
#define IDC_STATIC_JUNCTIONNUM          1215
#define IDC_STATIC_EDIT_PIE             1216
#define IDC_STATIC_POWERNUM             1216
#define IDC_STATIC_TEXT                 1216
#define IDC_STATIC_EDIT_ROUNDRECT       1217
#define IDC_STATIC_NETLABELNUM          1217
#define IDC_STATIC_REGION               1217
#define IDC_STATIC_EDIT_ELLIPTICALARC   1218
#define IDC_STATIC_PORTNUM              1218
#define IDC_STATIC_POLYGON              1218
#define IDC_STATIC_EDIT_RECT            1219
#define IDC_STATIC_SHEETSYMBOLNUM       1219
#define IDC_STATIC_EDIT_SHEETSYMBOL     1220
#define IDC_STATIC_BUSNUM               1220
#define IDC_STATIC_DIMENSION            1220
#define IDC_STATIC_EDIT_SHEETENTRY      1221
#define IDC_STATIC_BUSENTRYNUM          1221
#define IDC_STATIC_COORDINATE           1221
#define IDC_STATIC_EDIT_OFFSHEET        1222
#define IDC_STATIC_TEXTNUM              1222
#define IDC_STATIC_HOLE                 1222
#define IDC_STATIC_EDIT_POWER           1223
#define IDC_STATIC_TEXTFRAMENUM         1223
#define IDC_STATIC_SQUARE_HOLE          1223
#define IDC_STATIC_EDIT_PORT            1224
#define IDC_STATIC_POLYLINENUM          1224
#define IDC_STATIC_CONNECTION           1224
#define IDC_STATIC_EDIT_NETLABEL        1225
#define IDC_STATIC_ARCNUM               1225
#define IDC_STATIC_DRC_VIOLATION        1225
#define IDC_STATIC_EDIT_BUS             1226
#define IDC_STATIC_PIENUM               1226
#define IDC_STATIC_EDIT_BUSENTRY        1227
#define IDC_STATIC_POLYGONNUM           1227
#define IDC_STATIC_EDIT_WIRE            1228
#define IDC_STATIC_RECTNUM              1228
#define IDC_STATIC_EDIT_TEXTFRAME       1229
#define IDC_STATIC_ROUNDRECTNUM         1229
#define IDC_STATIC_EDIT_JUNCTION        1230
#define IDC_STATIC_ELLIPSEFILLNUM       1230
#define IDC_STATIC_EDIT_TEXT            1231
#define IDC_STATIC_ELLIPSENUM           1231
#define IDC_STATIC_EDIT_BEZIER          1232
#define IDC_STATIC_BEZIERNUM            1232
#define IDC_STATIC_EDIT_GRAPHIC         1233
#define IDC_STATIC_GRAPHICNUM           1233
#define IDC_STATIC_EDIT_LINE            1234
#define IDC_STATIC_EDIT_ELLIPSEFILL     1235
#define IDC_BUTTON_MENU                 1237
#define IDC_COMBO_JUSTIFICATION1        1244
#define IDC_COMBO6                      1245
#define IDC_COMBO_JUSTIFICATION2        1245
#define IDC_CHECK5                      1247
#define IDC_CHECK_PLATED                1247
#define IDC_CHECK_SOLID                 1247
#define IDC_CHECK_SIZE                  1247
#define IDC_LIST_TEXTOTHERS             1249
#define IDC_STATIC_PACKAGE              1250
#define IDC_BUTTON_CHOOSEPACKAGE        1251
#define IDC_EDIT_MODELNAME              1252
#define IDC_STATIC_FILL                 1254
#define IDC_STATIC_LINE                 1255
#define IDC_STATIC_SLOT_HOLE            1255
#define IDC_STATIC_PIN                  1256
#define IDC_SPIN_PARTNUM                1259
#define IDC_STATIC_PINDEMO              1260
#define IDC_EDIT_COMMENT                1262
#define IDC_BUTTON_ADDITEM              1263
#define IDC_BUTTON_DELETEITEM           1264
#define IDC_FONT_FONT                   1266
#define IDC_FONT_BOLD                   1267
#define IDC_FONT_ITALIC                 1268
#define IDC_FONT_UNDERLINE              1269
#define IDC_FONT_SAMPLE                 1270
#define IDC_BUTTON_EDIT_PIN             1271
#define IDC_EDIT_TEXTFRAME_TEXT         1274
#define IDC_REPORT_PIN                  1275
#define IDC_COMBO_SHEET                 1276
#define IDC_RADIO_SHEET                 1277
#define IDC_RADIO1                      1278
#define IDC_RADIO2                      1279
#define IDC_RADIO3                      1280
#define IDC_RADIO4                      1281
#define IDC_RADIO5                      1282
#define IDC_RADIO6                      1283
#define IDC_RADIO7                      1284
#define IDC_RADIO_SOLDER                1285
#define IDC_RADIO22                     1285
#define IDC_RADIO_HATCH_STYLE4          1285
#define IDC_BUTTON_SHEETSYMBOL          1286
#define IDC_RADIO23                     1286
#define IDC_RADIO_SOLDER1               1286
#define IDC_BUTTON_PORT                 1287
#define IDC_BUTTON_NETLABEL             1288
#define IDC_BUTTON_POWER                1289
#define IDC_RADIO8                      1290
#define IDC_RADIO9                      1291
#define IDC_RADIO10                     1292
#define IDC_RADIO11                     1293
#define IDC_RADIO12                     1294
#define IDC_RADIO13                     1295
#define IDC_RADIO14                     1296
#define IDC_RADIO15                     1297
#define IDC_RADIO16                     1298
#define IDC_RADIO17                     1299
#define IDC_RADIO18                     1300
#define IDC_RADIO19                     1301
#define IDC_RADIO20                     1302
#define IDC_RADIO21                     1303
#define IDC_BUTTON_JUNCTION             1303
#define IDC_BUTTON_WIRE                 1305
#define IDC_BUTTON_COMP                 1306
#define IDC_STATIC_ELEMENT              1307
#define IDC_STATIC_LINENUM              1308
#define IDC_BUTTON_POLYGON              1311
#define IDC_BUTTON_PIE                  1312
#define IDC_BUTTON_ARC                  1313
#define IDC_BUTTON_POLYLINE             1314
#define IDC_RADIO_OPEN                  1314
#define IDC_BUTTON_TEXTFRAME            1315
#define IDC_CHECK_MIRROR                1315
#define IDC_BUTTON_BUSENTRY             1316
#define IDC_COMBO_HJ                    1316
#define IDC_COMBO_VJ                    1317
#define IDC_BUTTON_BUS                  1318
#define IDC_BUTTON1                     1318
#define IDC_BUTTON_PRINT                1318
#define IDC_BUTTON_DEFAULT              1318
#define IDC_COMBO_PAPERSIZE             1319
#define IDC_BUTTON_SEARCH               1319
#define IDC_BUTTON7                     1319
#define IDC_RADIO_ORIENTATION           1320
#define IDC_BUTTON8                     1320
#define IDC_BUTTON_GRAPHIC              1321
#define IDC_RADIO_COLOR                 1321
#define IDC_BUTTON9                     1321
#define IDC_BUTTON_BEZIER               1322
#define IDC_EDIT_V_MARGIN               1322
#define IDC_BUTTON10                    1322
#define IDC_BUTTON_ELLIPSE              1323
#define IDC_EDIT_H_MARGIN               1323
#define IDC_BUTTON11                    1323
#define IDC_BUTTON_ROUNDRECT            1324
#define IDC_CHECK_H_CENTER              1324
#define IDC_BUTTON12                    1324
#define IDC_BUTTON_ELLIPSEFILL          1325
#define IDC_CHECK_V_CENTER              1325
#define IDC_BUTTON13                    1325
#define IDC_BUTTON_RECT                 1326
#define IDC_EDIT_CORRECTION_X           1326
#define IDC_BUTTON14                    1326
#define IDC_EDIT_CORRECTION_Y           1327
#define IDC_BUTTON15                    1327
#define IDC_RADIO_EXTENT                1328
#define IDC_BUTTON16                    1328
#define IDC_BUTTON_PRINT_PREVIEW        1329
#define IDC_BUTTON17                    1329
#define IDC_BUTTON_SETUP_PRINTER        1330
#define IDC_BUTTON18                    1330
#define IDC_STATIC_PRINT_PORTRAIT       1331
#define IDC_BUTTON19                    1331
#define IDC_STATIC_PRINT_LANDSCAPE      1332
#define IDC_BUTTON20                    1332
#define IDC_STATIC_S01                  1333
#define IDC_BUTTON21                    1333
#define IDC_STATIC_S02                  1334
#define IDC_STATIC_S03                  1335
#define IDC_STATIC_S04                  1336
#define IDC_STATIC_SHEET                1337
#define IDC_STATIC_WINDOW               1338
#define IDC_STATIC_AD6                  1338
#define IDC_BUTTON3                     1339
#define IDC_BUTTON_SETUP_ADVANCED       1339
#define IDC_BUTTON2                     1340
#define IDC_BUTTON5                     1341
#define IDC_BUTTON6                     1342
#define IDC_BUTTON4                     1343
#define IDC_COMBO_COMP_NAME             1345
#define IDC_COMBO_COMP_PACKAGE          1346
#define IDC_COMBO_COMP_PARTID           1347
#define IDC_BUTTON_HISTORY              1348
#define IDC_LIST_LIB                    1350
#define IDC_LIST_COMP                   1353
#define IDC_COMBO_PACKAGE               1354
#define IDC_LIST_NET                    1354
#define IDC_STATIC_COMP_PREVIEW         1355
#define IDC_STATIC_PACKAGE_PREVIEW      1356
#define IDC_STATIC_INFO                 1357
#define IDC_RADIO_COMPANY               1359
#define IDC_RADIO_FUNCTION              1360
#define IDC_TREE_LIBRARY                1364
#define IDC_CHECK_MATCH                 1365
#define IDC_LIST_USER_LIBRARY           1366
#define IDC_LIST_USERLIB                1369
#define IDC_LIST                        1371
#define IDC_LIST1                       1372
#define IDC_LIST_E                      1372
#define IDC_LIST_PLANE_NET              1372
#define IDC_NET_LIST                    1372
#define IDC_RADIO_NEWLIB                1373
#define IDC_LIST_A                      1373
#define IDC_LIST_PLANE_PIN              1373
#define IDC_PIN_LIST                    1373
#define IDC_EDIT2                       1374
#define IDC_EDIT_X                      1374
#define IDC_EDIT_BACKUP                 1374
#define IDC_EDIT_HOLE_ROTATION          1374
#define IDC_EDIT_REMOVE_ISLAND          1374
#define IDC_EDIT_LINEWIDTH              1374
#define IDC_EDIT_PREFIX                 1374
#define IDC_EDIT_XX1                    1374
#define IDC_EDIT_NETNAME                1374
#define IDC_EDIT_MAX_RADIUS             1374
#define IDC_EDIT_DESC                   1374
#define IDC_EDIT_COMPNAME               1374
#define IDC_EDIT3                       1375
#define IDC_EDIT_MODENUM                1375
#define IDC_EDIT_NAMEOFFSET             1375
#define IDC_EDIT_X1                     1375
#define IDC_EDIT_EXPANSION              1375
#define IDC_EDIT_STRING                 1375
#define IDC_EDIT_HOLE_WIDTH             1375
#define IDC_EDIT_MIN_LENGTH             1375
#define IDC_EDIT_TEXTWIDTH              1375
#define IDC_EDIT_SUFFIXX                1375
#define IDC_EDIT_YY1                    1375
#define IDC_EDIT_UNDO_BUFFER            1375
#define IDC_EDIT4                       1376
#define IDC_EDIT_PACK                   1376
#define IDC_EDIT_Y                      1376
#define IDC_EDIT_NUMBEROFFSET           1376
#define IDC_EDIT_ARC_PRECISION          1376
#define IDC_EDIT_LINEHEIGHT             1376
#define IDC_EDIT_XX2                    1376
#define IDC_EDIT_LOAD_PACKAGE_X         1376
#define IDC_EDIT6                       1377
#define IDC_EDIT_WIDTH                  1377
#define IDC_EDIT_Y1                     1377
#define IDC_EDIT_PASTE                  1377
#define IDC_EDIT_TEXTHEIGHT             1377
#define IDC_EDIT_YY2                    1377
#define IDC_EDIT_POUR_GAP               1377
#define IDC_EDIT_LOAD_PACKAGE_Y         1377
#define IDC_EDIT7                       1378
#define IDC_EDIT_Y2                     1378
#define IDC_EDIT_SOLDER                 1378
#define IDC_RADIO_NEWCOMP               1379
#define IDC_RADIO_OLDLIB                1380
#define IDC_RADIO_OLDCOMP               1381
#define IDC_STATIC_PART                 1383
#define IDC_STATIC_PART2                1385
#define IDC_BUTTON_CHECK                1386
#define IDC_STATIC_OLDNAME              1387
#define IDC_RADIO_PART                  1388
#define IDC_RADIO_MODE                  1391
#define IDC_RADIO_MULTIPART             1392
#define IDC_RADIO_MULTIMODE             1393
#define IDC_COMBO_PINPOSITION           1394
#define IDC_COMBO_SCOPE                 1396
#define IDC_COMBO_OBJECT                1397
#define IDC_CHECK_CASE                  1398
#define IDC_CHECK_WHOLEWORD             1399
#define IDC_CHECK_WORD                  1399
#define IDC_CHECK_JUMP                  1400
#define IDC_CHECK_PROMPT                1401
#define IDC_COMBO1                      1402
#define IDC_COMBO_CURSOR                1402
#define IDC_COMBO_ORDER                 1402
#define IDC_COMBO_LAYER                 1402
#define IDC_COMBO_UNIT                  1402
#define IDC_COMBO_STARTLAYER            1402
#define IDC_COMBO_ID_LAYER              1402
#define IDC_COMBO_NAME                  1402
#define IDC_COMBO_TOPOLOGY              1402
#define IDC_STATIC_GRIDCOLOR            1403
#define IDC_COMBO_NET                   1403
#define IDC_COMBO5                      1403
#define IDC_COMBO_ID_AUTOPOSITION       1403
#define IDC_COMBO_SIZEUNIT              1403
#define IDC_COMBO_ENDLAYER              1404
#define IDC_CHECK_AUTOJUNC              1404
#define IDC_COMBO_C_LAYER               1404
#define IDC_COMBO8                      1404
#define IDC_COMBO_POUR_STYLE            1404
#define IDC_COMBO_PRECISION             1404
#define IDC_COMBO7                      1405
#define IDC_CHECK_AUTOWIRE              1405
#define IDC_COMBO_C_AUTOPOSITION        1405
#define IDC_CHECK_AUTODIAGRAM           1406
#define IDC_COMBO_COMP_LAYER            1406
#define IDC_CHECK_BACKUP                1407
#define IDC_STATIC_JUNCCOLOR            1408
#define IDC_STATIC_AUTOJUNCCOLOR        1408
#define IDC_STATIC_SELCOLOR             1409
#define IDC_CHECK_CLEARSEL              1410
#define IDC_RADIO_DIAGRAM               1411
#define IDC_STATIC_ORDER1               1412
#define IDC_STATIC_ORDER2               1413
#define IDC_STATIC_ORDER3               1414
#define IDC_STATIC_ORDER4               1415
#define IDC_RICHEDIT2                   1417
#define IDC_PLACEHOLDER                 1418
#define IDC_PROPERTY_GRID               1419
#define IDC_STATIC_MARKUP               1421
#define IDC_CHECK_LOCKED                1422
#define IDC_CHECK_KEEPOUT               1423
#define IDC_CHECK_EGRID_ENABLE          1423
#define IDC_CHECK_ALL_LAYER             1424
#define IDC_CHECK_BOARD_CUTOUT          1424
#define IDC_CHECK3                      1425
#define IDC_CHECK_OUTLINE               1425
#define IDC_SINGAL_LAYER_USESTACK       1425
#define IDC_CHECK_POLYGON_CUTOUT        1425
#define IDC_CHECK_LOCK_STRING           1425
#define IDC_CHECK_REMOVE_NECK           1425
#define IDC_CHECK_STACK_LAYER_ONLY      1425
#define IDC_CHECK_POLYGON_HIGHLIGHT     1425
#define IDC_CHECK_FILLCOLOR             1425
#define IDC_CHECK_START                 1425
#define IDC_CHECK_SHOW_SHEET            1426
#define IDC_PLANE_USESTACK              1426
#define IDC_CHECK_LOCK                  1426
#define IDC_CHECK_LOCK_SHEET            1427
#define IDC_MECH_LAYER_USESTACK         1427
#define IDC_CHECK10                     1427
#define IDC_CHECK_AUTO                  1427
#define IDC_COMBO_DESIGNATOR_DISPLAY    1428
#define IDC_STATIC_EDIT_TRACK           1429
#define IDC_EDIT_X2                     1430
#define IDC_EDIT_TRACKWIDTH             1431
#define IDC_CHECK_TOP                   1432
#define IDC_CHECK_BOTTOM                1433
#define IDC_RADIO_EXPANSION             1434
#define IDC_CHECK4                      1435
#define IDC_CHECK_TENTING_TOP           1435
#define IDC_CHECK_FILE_IMPORT           1435
#define IDC_CHECK_END                   1435
#define IDC_CHECK6                      1436
#define IDC_STATIC_EDIT_FILL            1436
#define IDC_CHECK_TENTING_BOTTOM        1436
#define IDC_CHECK_FILE_EXPORT           1436
#define IDC_STATIC_EDIT_DIMENSION       1437
#define IDC_STATIC_EDIT_COORDINATE      1438
#define IDC_STATIC_EDIT_LDIMENSION      1439
#define IDC_RADIO_TRUETYPE              1442
#define IDC_CHECK_BOLD                  1443
#define IDC_CHECK_ITALIC                1444
#define IDC_CHECK_INVERT                1445
#define IDC_RADIO_C_FONT                1446
#define IDC_STATIC_INVERT               1447
#define IDC_STATIC_INVERTBORDER         1448
#define IDC_STATIC_BOLD                 1449
#define IDC_STATIC_ITALIC               1450
#define IDC_RADIO_STROKE                1451
#define IDC_STATIC_SELECTION            1452
#define IDC_RADIO_C_STROKE              1452
#define IDC_STATIC_C_INVERT             1453
#define IDC_BUTTON_ADD_LAYER            1454
#define IDC_CHECK_C_INVERT              1454
#define IDC_BUTTON_ADD_PLANE            1455
#define IDC_STATIC_C_INVERTBORDER       1455
#define IDC_BUTTON_DELETE               1456
#define IDC_STATIC_C_BOLD               1456
#define IDC_BUTTON_MOVEUP               1457
#define IDC_CHECK_C_BOLD                1457
#define IDC_BUTTON_MOVEDOWN             1458
#define IDC_STATIC_C_ITALIC             1458
#define IDC_PCB_LAYER_STACK             1459
#define IDC_CHECK_C_ITALIC              1459
#define IDC_STATIC_NUM                  1460
#define IDC_SINGAL_LAYER                1461
#define IDC_PLANE                       1462
#define IDC_MECH_LAYER                  1463
#define IDC_MASK_LAYER                  1464
#define IDC_OTHER_LAYER                 1465
#define IDC_CONTROL_LAYER               1466
#define IDC_SILK_LAYER                  1467
#define IDC_SINGAL_ALLON                1469
#define IDC_SINGAL_ALLOFF               1470
#define IDC_STATIC_EDIT_REGION          1470
#define IDC_SINGAL_USEDON               1471
#define IDC_STATIC_KEEPOUT              1471
#define IDC_PLANE_ALLON                 1472
#define IDC_STATIC_NET                  1472
#define IDC_PLANE_ALLOFF                1473
#define IDC_STATIC_LAYER                1473
#define IDC_PLANE_USEDON                1474
#define IDC_MECH_ALLON                  1475
#define IDC_RADIO_HOLESHAPE             1475
#define IDC_MECH_ALLOFF                 1476
#define IDC_EDIT_PCB_DESIGNATOR         1476
#define IDC_MECH_USEDON                 1477
#define IDC_RADIO_PAD_MODE              1477
#define IDC_MASK_ALLON                  1478
#define IDC_STATIC_TOP                  1478
#define IDC_MASK_ALLOFF                 1479
#define IDC_STATIC_MID                  1479
#define IDC_MASK_USEDON                 1480
#define IDC_STATIC_BOTTOM               1480
#define IDC_OTHER_ALLON                 1481
#define IDC_RADIO_PASTE                 1481
#define IDC_OTHER_ALLOFF                1482
#define IDC_RADIO_PAD_MODE2             1482
#define IDC_OTHER_USEDON                1483
#define IDC_STATIC_HOLE_ROTATION        1483
#define IDC_SILK_ALLON                  1484
#define IDC_STATIC_HOLE_WIDTH           1484
#define IDC_SILK_ALLOFF                 1485
#define IDC_RADIO_HOLESHAPE1            1485
#define IDC_SILK_USEDON                 1486
#define IDC_RADIO_HOLESHAPE2            1486
#define IDC_CONTROL_ALLON               1487
#define IDC_RADIO_PASTE1                1487
#define IDC_CONTROL_ALLOFF              1488
#define IDC_TAB_CTRL                    1488
#define IDC_SINGAL_USEDON7              1489
#define IDC_CONTROL_USEDON              1489
#define IDC_STATIC_PAD                  1490
#define IDC_ALLON                       1490
#define IDC_ALLOFF                      1491
#define IDC_SILK_USEDON2                1492
#define IDC_USEDON                      1492
#define IDC_CHECK1                      1492
#define IDC_CHECK_ID_HIDE               1492
#define IDC_CHECK_PRIMITIVE_LOCK        1492
#define IDC_CHECK_HIDE_CONNECTION       1492
#define IDC_CHECK_ALLPAD                1492
#define IDC_CHECK_RATSNEST_ENABLE       1492
#define IDC_CHECK_GLOBLE                1492
#define IDC_CHECK_GLOBAL                1492
#define IDC_CHECK_WIDTH                 1492
#define IDC_CHECK_ORIENTATION           1492
#define IDC_CHECK2                      1493
#define IDC_CHECK_ID_MIRROR             1493
#define IDC_CHECK_REMOVE_ISLAND         1493
#define IDC_CHECK_REMOVE_LOOP           1493
#define IDC_CHECK_ALLVIA                1493
#define IDC_CHECK_ONLINE_DRC            1493
#define IDC_CHECK_COLOR                 1493
#define IDC_CHECK_C_HIDE                1494
#define IDC_CHECK7                      1494
#define IDC_CHECK_IGNORE_VIOLATION      1494
#define IDC_CHECK_SELECTION             1494
#define IDC_CHECK_C_MIRROR              1495
#define IDC_CHECK8                      1495
#define IDC_CHECK_REMOVE_DEAD           1495
#define IDC_EDIT_ID                     1496
#define IDC_EDIT_C                      1497
#define IDC_RADIO_ID_FONT               1498
#define IDC_RADIO_ID_STROKE             1499
#define IDC_COMBO_ID_FONT               1500
#define IDC_CHECK_ID_BOLD               1501
#define IDC_CHECK_ID_ITALIC             1502
#define IDC_CHECK_ID_INVERT             1503
#define IDC_EDIT_ID_INVERT              1504
#define IDC_STATIC_ID_BOLD              1505
#define IDC_STATIC_ID_ITALIC            1506
#define IDC_STATIC_ID_INVERT            1507
#define IDC_STATIC_ID_INVERTBORDER      1508
#define IDC_RADIO_FILLMODE              1510
#define IDC_RADIO_FILLMODE1             1510
#define IDC_STATIC_EDIT_POLYGON         1513
#define IDC_STATIC_EDIT_POLYGON1_1      1514
#define IDC_STATIC_EDIT_POLYGON1_2      1515
#define IDC_STATIC_EDIT_POLYGON1_3      1516
#define IDC_STATIC_EDIT_POLYGON1_4      1517
#define IDC_STATIC_EDIT_POLYGON2        1518
#define IDC_STATIC_EDIT_POLYGON3        1519
#define IDC_RADIO_FILLMODE2             1520
#define IDC_RADIO_FILLMODE3             1521
#define IDC_RADIO_PAD_STYLE1            1522
#define IDC_RADIO_HATCH_STYLE1          1523
#define IDC_STATIC_TRACK_WIDTH          1524
#define IDC_STATIC_GRID_SIZE            1525
#define IDC_STATIC_PAD_STYLE            1526
#define IDC_RADIO_PAD_STYLE2            1527
#define IDC_STATIC_HATCH_STYLE          1528
#define IDC_RADIO_HATCH_STYLE2          1529
#define IDC_RADIO_HATCH_STYLE3          1530
#define IDC_STATIC_REMOVE_ISLAND        1531
#define IDC_STATIC_ARC_PRECISION        1532
#define IDC_STATIC_EDIT_DIMENSION_LINEAR 1534
#define IDC_COMBO_FORMAT                1535
#define IDC_STATIC_BOARD                1536
#define IDC_BUTTON_DEFINE               1537
#define IDC_STATIC_XX1                  1538
#define IDC_STATIC_XX2                  1539
#define IDC_STATIC_YY1                  1540
#define IDC_STATIC_YY2                  1541
#define IDC_RADIO_BOARD                 1542
#define IDC_RADIO_XY                    1543
#define IDC_BUTTON_APPLY                1546
#define IDC_PCB_LAYER_SET_NAME          1547
#define IDC_PCB_LAYER_SET_SHOW          1548
#define IDC_BUTTON_WRITE                1549
#define IDC_BUTTON_LOAD                 1550
#define IDC_STATIC_COMPONENT            1551
#define IDC_STATIC_COMPONENT_TOP        1552
#define IDC_STATIC_COMPONENT_BOTTOM     1553
#define IDC_TAB_PLANE                   1554
#define IDC_STATIC_PLANE                1555
#define IDC_STATIC_PLANE_NET            1555
#define IDC_STATIC_PLANE_PIN            1556
#define IDC_STATIC_NOTFOUND             1557
#define IDC_NET_EDIT                    1558
#define IDC_NET_ADD                     1559
#define IDC_NET_DELETE                  1560
#define IDC_PIN_EDIT                    1561
#define IDC_DATETIMEPICKER1             1564
#define IDC_STATIC_EDIT_NET             1565
#define IDC_LAYER_TRACK_WIDTH           1566
#define IDC_PINS_OLD                    1567
#define IDC_TXT_URL2                    1567
#define IDC_PINS_NEW                    1568
#define IDC_BUTTON_USER_SHEET           1568
#define IDC_REPORT_NET                  1569
#define IDC_REPORT_COMP                 1570
#define IDC_REPORT_NETLIST              1571
#define IDC_BUTTON_CLEAR                1571
#define IDC_STATIC_INIT                 1572
#define IDC_MISSING_COMP                1573
#define IDC_PINS                        1574
#define IDC_STATIC_CLEARANCE            1575
#define IDC_EDIT_CLEARANCE              1576
#define IDC_STATIC_WIDTH                1577
#define IDC_STATIC_CORNER1              1578
#define IDC_STATIC_CORNER2              1579
#define IDC_STATIC_CORNER3              1580
#define IDC_EDIT_SETBACK                1581
#define IDC_STATIC_SETBACK              1582
#define IDC_PCB_RULES_LAYER             1583
#define IDC_PCB_RULES_LAYER2            1584
#define IDC_PCB_RULES_PRIORITY          1584
#define IDC_EDIT_PRIORITY               1586
#define IDC_STATIC_SOLDER               1588
#define IDC_STATIC_PASTE                1589
#define IDC_STATIC_INTERNAL3            1590
#define IDC_STATIC_INTERNAL1            1591
#define IDC_STATIC_INTERNAL2            1592
#define IDC_RADIO_CONDUCTOR_2           1593
#define IDC_RADIO_CONDUCTOR_4           1594
#define IDC_STATIC_CONDUCTOR            1595
#define IDC_STATIC_EXPANSION            1596
#define IDC_STATIC_INTERNAL_EXPANSION   1596
#define IDC_STATIC_INTERNAL_GAP         1597
#define IDC_EDIT_INTERNAL_WIDTH         1598
#define IDC_EDIT_INTERNAL_GAP           1599
#define IDC_EDIT_INTERNAL_EXPANSION     1600
#define IDC_STATIC_INTERNAL_WIDTH       1601
#define IDC_STATIC_POLYGON1             1602
#define IDC_STATIC_POLYGON2             1603
#define IDC_EDIT_POLYGON_WIDTH          1604
#define IDC_STATIC_POLYGON_WIDTH        1605
#define IDC_RADIO_ACTION                1607
#define IDC_RADIO_STYLE                 1608
#define IDC_RADIO_STYLE2                1609
#define IDC_RADIO_ACTION2               1610
#define IDC_RADIO_SIZE                  1611
#define IDC_RADIO_SIZE2                 1612
#define IDC_SHEET_SELECT                1613
#define IDC_SHEET_CLEAR                 1614
#define IDC_BUTTON_XY                   1615
#define IDC_RADIO_SCOPE                 1616
#define IDC_CHECK_FONT                  1617
#define IDC_CHECK_STYLE                 1618
#define IDC_CHECK_TEXTCOLOR             1619
#define IDC_CHECK_BORDERCOLOR           1620
#define IDC_CHECK_ALIGNMENT             1621
#define IDC_CHECK_IO                    1622
#define IDC_BUTTON                      1623
#define IDC_BUTTON_ID_GLOBAL            1623
#define IDC_BUTTON_COMMENT_GLOBAL       1624
#define IDC_RADIO_ID_SUFFIX             1625
#define IDC_EDIT_ARC                    1626
#define IDC_EDIT_LIBNUM                 1627
#define IDC_STATIC_LIBNAME              1628
#define IDC_RICHEDIT_REF                1629
#define IDC_BUTTON_SAVEBACK             1630
#define IDC_BUTTON_REFRESH              1631
#define IDC_STATIC_COMPNAME             1632
#define ID_PICKUP_TIMER                 32750
#define ID_SELECTION_TIMER              32751
#define ID_PANEPROPERTIES_CATEGORIZED   32771
#define ID_PANEPROPERTIES_ALPHABETIC    32772
#define ID_PANEPROPERTIES_PAGES         32773
#define ID_FILE_SAVE_ALL                32774
#define ID_EDIT_PLATFORM                32777
#define ID_SOLUTION_PROPERTIES          32778
#define ID_SOLUTION_ADDNEWFOLDER        32779
#define ID_SOLUTION_UNHIDEALL           32780
#define ID_POPUP_AUTOHIDE               32782
#define ID_POPUP_HIDE                   32783
#define ID_POPUP_FLOATING               32784
#define ID_POPUP_DOCKABLE               32785
#define ID_THEME_VC6                    32786
#define ID_THEME_VC7                    32787
#define ID_THEME_VC8                    32788
#define ID_SKINFRAMEWORK_VISTABLUE      32789
#define ID_SKINFRAMEWORK_VISTABLACK     32790
#define ID_SKINFRAMEWORK_SYSTEM         32791
#define ID_BUTTON32792                  32792
#define ID_FILE_IMPORT                  32795
#define ID_VIEW_FIT_DOCUMENT            32796
#define ID_FILE_IMPORT_AUTOCAD          32797
#define ID_VIEW_FIT_ALL_OBJECTS         32798
#define ID_VIEW_AREA                    32799
#define ID_VIEW_SELECTED_OBJECTS        32801
#define ID_VIEW_50                      32805
#define ID_VIEW_100                     32806
#define ID_VIEW_200                     32807
#define ID_VIEW_400                     32808
#define ID_VIEW_ZOOM_IN                 32809
#define ID_VIEW_ZOOM_OUT                32810
#define ID_VIEW_ZOOM_LAST               32811
#define ID_VIEW_PAN                     32812
#define ID_VIEW_REFRESH                 32813
#define ID_32814                        32814
#define ID_EDIT_STATE                   32815
#define ID_VIEW_TOOLBAR_SCH_STANDARD    32815
#define ID_EDIT_FIND_EX                 32816
#define ID_32816                        32816
#define ID_GOTO_URL                     32817
#define ID_WORKSPACEPANELS_SCH          32817
#define ID_WINDOW_AUTOHIDEALL           32818
#define ID_VIEW_WORKSPACE_SCHLIST       32818
#define ID_32819                        32819
#define ID_VIEW_DESKTOP_DEFAULT         32820
#define ID_WINDOW_CLOSE_ALL             32821
#define ID_VIEW_DEVICES_VIEW            32821
#define ID_WINDOW_MORE                  32822
#define ID_VIEW_HOME                    32822
#define ID_VIEW_COMMAND_STATUS          32823
#define ID_32824                        32824
#define ID_VIEW_GRIDS_TOGGLE_VISIBLE    32825
#define ID_VIEW_TOGGLE_UNITS            32826
#define ID_WINDOW_TILE                  32827
#define ID_WINDOW_ARRANGE_HORZ          32830
#define ID_WINDOW_ARRANGE_VERT          32831
#define ID_WINDOW_CLOSE                 32832
#define ID_HELP_KNOWLEDGE_BASE          32835
#define ID_VIEW_FIT_BOARD               32838
#define ID_VIEW_FLIP_BOARD              32840
#define ID_TO_PCB                       32841
#define ID_TO_SCH                       32842
#define ID_DOC_TAB                      32847
#define ID_SHEET_TAB                    32848
#define ID_SHEET_TAB_REFRESH            32849
#define ID_VIEW_CENTER                  32853
#define ID_GRID_TOGGLE_VISIBLE          32855
#define ID_GRID_CYCLE_SNAP              32856
#define ID_GRID_TOGGLE_ELECTRIC         32857
#define ID_32858                        32858
#define ID_FILE_EXPORT_AD6_ASCII_SCH    32864
#define ID_FILE_EXPORT_99ASCII_SCH      32865
#define ID_FILE_IMPORT_AD6ASCII_SCH     32866
#define ID_FILE_IMPORT_99ASCII_SCH      32867
#define ID_32868                        32868
#define ID_FILE_EXPORT_AD6ASCII_PCB     32869
#define ID_FILE_EXPORT_99ASCII_PCB      32870
#define ID_FILE_IMPORT_AD6ASCII_PCB     32871
#define ID_FILE_IMPORT_99ASCII_PCB      32872
#define ID_DESIGN_OPTION                32875
#define ID_PLACE_BUS                    32876
#define ID_PLACE_BUSENTRY               32877
#define ID_PLACE_PART                   32878
#define ID_PLACE_JUNCTION               32879
#define ID_PLACE_NETLABEL               32882
#define ID_PLACE_POWER                  32883
#define ID_PLACE_OFFSHEET               32884
#define ID_PLACE_SHEETSYMBOL            32885
#define ID_PLACE_SHEETENTRY             32886
#define ID_PLACE_TEXT                   32887
#define ID_PLACE_TEXTFRAME              32888
#define ID_32889                        32889
#define ID_PLACE_ARC                    32890
#define ID_PLACE_ELLIPTICAL_ARC         32892
#define ID_PLACE_ELLIPTICAL_FILL        32893
#define ID_PLACE_PIE                    32894
#define ID_PLACE_RECT                   32896
#define ID_PLACE_ROUNDRECT              32897
#define ID_PLACE_POLYGON                32898
#define ID_PLACE_BEZIER                 32899
#define ID_PLACE_IMAGE                  32900
#define ID_EDIT_FIND_NEXT               32903
#define ID_32904                        32904
#define ID_32905                        32905
#define ID_EDIT_SELECT_INSIDE           32906
#define ID_EDIT_SELECT_OUTSIDE          32907
#define ID_EDIT_SELECT_CONNECTION       32908
#define ID_EDIT_DESELECT_INSIDE         32909
#define ID_EDIT_DESELECT_OUTSIDE        32910
#define ID_EDIT_BREAK_WIRE              32911
#define ID_EDIT_DUPLICATE               32912
#define ID_EDIT_JUMP                    32916
#define ID_EDIT_SELECTION_MEMORY        32917
#define ID_DESIGN_LIB_BROWSE            32918
#define ID_DESIGN_LIB_MAKE              32919
#define ID_32920                        32920
#define ID_REPORT_BOARD                 32922
#define ID_REPORT_BOM                   32923
#define ID_32924                        32924
#define ID_32925                        32925
#define ID_REPORT_NET                   32926
#define ID_ROUTE_ALL                    32928
#define ID_ROUTE_NET                    32929
#define ID_ROUTE_CONNECTION             32930
#define ID_ROUTE_AREA                   32931
#define ID_ROUTE_ROOM                   32934
#define ID_ROUTE_COMPONENT              32935
#define ID_ROUTE_SETUP                  32936
#define ID_DESIGN_SCH                   32938
#define ID_DESIGN_IMPORT_CHANGE         32939
#define ID_DESIGN_RULE_WIZARD           32941
#define ID_DESIGN_BOARD_SHEET           32946
#define ID_32953                        32953
#define ID_32954                        32954
#define ID_PERFERENCE                   32956
#define ID_VIEW_FILTERED_OBJECTS        32958
#define ID_PLACE_PORT                   32959
#define ID_SELECTION_1                  32960
#define ID_SELECTION_2                  32961
#define ID_SELECTION_3                  32962
#define ID_SELECTION_4                  32963
#define ID_SELECTION_5                  32964
#define ID_SELECTION_6                  32965
#define ID_SELECTION_7                  32966
#define ID_SELECTION_8                  32967
#define ID_SELECTION_9                  32968
#define ID_SELECTION_10                 32969
#define ID_SELECTION_11                 32970
#define ID_SELECTION_12                 32971
#define ID_SELECTION_13                 32972
#define ID_SELECTION_14                 32973
#define ID_SELECTION_15                 32974
#define ID_SELECTION_16                 32975
#define ID_SELECTION_17                 32976
#define ID_SELECTION_18                 32977
#define ID_SELECTION_19                 32978
#define ID_SELECTION_20                 32979
#define ID_REPORT_ELEMENTS              32986
#define ID_FILE_OPEN_ONE                32989
#define ID_FILE_SAVE_ONE                32991
#define ID_FILE_PRINT_SETUP_SCH         32992
#define ID_PLACE_WIRE                   32994
#define ID_PLACE_POLYLINE               32995
#define ID_PLACE_ARCEDGED               32998
#define ID_PLACE_ARCCENTER              32999
#define ID_PLACE_ELLIPTICAL_ARCCENTER   33000
#define ID_PLACE_ELLIPTICAL_ARCEDGED    33001
#define ID_PLACE_EARC_CENTER            33002
#define ID_PLACE_EARC_DEGED             33003
#define ID_EDIT_DESELECT_ALL            33005
#define ID_EDIT_DELETE                  33006
#define ID_EDIT_CHANGE                  33007
#define ID_EDIT_MOVE                    33008
#define ID_EDIT_MOVE_SELECTION          33009
#define ID_LIB_BROWSE                   33010
#define ID_LIB_TRAN2                    33011
#define ID_LIB_TRAN1                    33012
#define ID_LIB_TRAN3                    33013
#define ID_LIB_TRAN4                    33014
#define ID_LIB_STATUS                   33015
#define ID_LIB_ADD                      33016
#define ID_LIB_DELETE                   33018
#define ID_LIB_EDIT                     33019
#define ID_LIB_LIST                     33020
#define ID_LIB_NEW                      33022
#define ID_LIB_COMBINE                  33023
#define ID_EDIT_MOVE_FRONT              33037
#define ID_EDIT_MOVE_BACK               33038
#define ID_EDIT_SELECTION_TOGGLE        33040
#define ID_EDIT_ALIGN_LEFT              33041
#define ID_EDIT_ALIGN_RIGHT             33042
#define ID_EDIT_ALIGN_HCENTER           33043
#define ID_EDIT_ALIGN_HPLACE            33044
#define ID_EDIT_ALIGN_TOP               33045
#define ID_EDIT_ALIGN_BOTTOM            33046
#define ID_EDIT_ALIGN_VCENTER           33047
#define ID_EDIT_ALIGN_VPLACE            33048
#define ID_AUTO_ANNOTATE                33054
#define ID_AUTO_ANNOTATE_RESET          33055
#define ID_AUTO_COMPILE                 33057
#define ID_EDIT_JUMP_ORIGIN             33058
#define ID_EDIT_JUMP_LOCATION           33059
#define ID_EDIT_JUMP_COMPONENT          33060
#define ID_EDIT_JUMP_1                  33062
#define ID_EDIT_JUMP_2                  33063
#define ID_EDIT_JUMP_3                  33064
#define ID_EDIT_JUMP_4                  33065
#define ID_EDIT_JUMP_5                  33066
#define ID_EDIT_JUMP_6                  33067
#define ID_EDIT_JUMP_7                  33068
#define ID_EDIT_JUMP_8                  33069
#define ID_EDIT_JUMP_9                  33070
#define ID_EDIT_JUMP_10                 33071
#define ID_EDIT_SETJUMP_1               33073
#define ID_EDIT_SETJUMP_2               33074
#define ID_EDIT_SETJUMP_3               33075
#define ID_EDIT_SETJUMP_4               33076
#define ID_EDIT_SETJUMP_5               33077
#define ID_EDIT_SETJUMP_6               33078
#define ID_EDIT_SETJUMP_7               33079
#define ID_EDIT_SETJUMP_8               33080
#define ID_EDIT_SETJUMP_9               33081
#define ID_EDIT_SETJUMP_10              33082
#define ID_PLACE_GROUND                 33083
#define ID_AUTO_BACKUP_TIMER            33085
#define ID_GRID_SETUP                   33087
#define ID_INDICATOR_ZOOMSLIDER         33096
#define ID_TAB_FILE_CLOSE               33096
#define ID_INDICATOR_ZOOM               33097
#define ID_PCB_VIEW_HIGHLIGHT           33098
#define ID_HELP_TIP                     33099
#define ID_HIGHLIGHT1                   33100
#define ID_HIGHLIGHT2                   33101
#define ID_HIGHLIGHT3                   33102
#define ID_HIGHLIGHT4                   33103
#define ID_HIGHLIGHT5                   33104
#define ID_HIGHLIGHT6                   33105
#define ID_VIEW_HIGHLIGHT               33106
#define ID_HIGHLIGHT_RESET              33107
#define ID_HIGHLIGHT_LIST               33108
#define ID_REPORT_BM1                   33109
#define ID_REPORT_BM2                   33110
#define ID_REPORT_ERR                   33111
#define ID_PCB_BOARD_OPTIONS            33112
#define ID_PCB_LAYER_SETUP              33113
#define ID_PCB_LAYER_STACK              33114
#define ID_STATUS_SNAP1                 33115
#define ID_STATUS_SNAP2                 33116
#define ID_STATUS_SNAP3                 33117
#define ID_STATUS_SNAP4                 33118
#define ID_STATUS_SNAP5                 33119
#define ID_STATUS_SNAP6                 33120
#define ID_STATUS_SNAP7                 33121
#define ID_STATUS_SNAP8                 33122
#define ID_STATUS_SNAP9                 33123
#define ID_STATUS_SNAP10                33124
#define ID_STATUS_SNAP11                33125
#define ID_STATUS_SNAP12                33126
#define ID_STATUS_SNAP13                33127
#define ID_PCB_VIEW_SNAP_SETUP          33128
#define ID_PCB_VIEW_SELECTED_OBJECTS    33129
#define ID_STATUS_VISIBLE1              33130
#define ID_STATUS_VISIBLE2              33131
#define ID_STATUS_VISIBLE3              33132
#define ID_STATUS_VISIBLE4              33133
#define ID_STATUS_VISIBLE5              33134
#define ID_STATUS_VISIBLE6              33135
#define ID_STATUS_VISIBLE7              33136
#define ID_STATUS_VISIBLE8              33137
#define ID_STATUS_VISIBLE9              33138
#define ID_STATUS_VISIBLE10             33139
#define ID_STATUS_VISIBLE11             33140
#define ID_STATUS_VISIBLE12             33141
#define ID_STATUS_VISIBLE13             33142
#define ID_PCB_LAYER_SET                33143
#define ID_PCB_LAYER_SET_ALL            33144
#define ID_PCB_LAYER_SET_SIGNAL         33145
#define ID_PCB_LAYER_SET_PLANE          33146
#define ID_PCB_LAYER_SET_NOSIGNAL       33147
#define ID_PCB_LAYER_SET_MECHANICAL     33148
#define ID_EDIT_ORIGIN_SET              33149
#define ID_EDIT_ORIGIN_RESET            33150
#define ID_EDIT_JUMP_CURRENT_ORIGIN     33151
#define ID_33152                        33152
#define ID_PCB_PLACE_ARC_CENTER         33153
#define ID_PCB_PLACE_ARC_EDGE           33154
#define ID_PCB_PLACE_ARC_CIRCLE         33156
#define ID_PCB_PLACE_FILL               33157
#define ID_PCB_PLACE_REGION             33158
#define ID_PCB_PLACE_TRACK              33159
#define ID_PCB_PLACE_STRING             33160
#define ID_PCB_PLACE_PAD                33161
#define ID_PCB_PLACE_VIA                33162
#define ID_PCB_PLACE_COMP               33163
#define ID_PCB_PLACE_COORDINATE         33164
#define ID_PCB_PLACE_DIMENSION          33165
#define ID_PCB_PLACE_POLYGON            33166
#define ID_PCB_PLACE_POLYGON_CUTOUT     33167
#define ID_PCB_LIB_BROWSE               33168
#define ID_PCB_LIB_LIST                 33169
#define ID_PCB_LIB_ADD                  33170
#define ID_PCB_LIB_DELETE               33171
#define ID_PCB_LIB_CHANGE               33172
#define ID_PCB_LIB_EDIT                 33173
#define ID_PCB_LIB_COMBINE              33174
#define ID_PCB_LIB_MAKE                 33175
#define ID_PCB_LIB_MAKELIB              33176
#define ID_PCB_NET_CREATE               33177
#define ID_PCB_NET_SAVE                 33178
#define ID_PCB_BOARD_SHAPE              33182
#define ID_PCB_BOARD_VERTEX             33183
#define ID_PCB_BOARD_MOVE               33184
#define ID_EDIT_SELECT_NET              33188
#define ID_PCB_EDIT_DUPLICATE           33190
#define ID_DOWNLOAD_ONLINE              33191
#define ID__33198                       33198
#define ID_33199                        33199
#define ID_REPORT_WIR                   33200
#define ID_REPORT_COMPNET               33203
#define ID_Menu33204                    33204
#define ID_PCB_EDIT_MOVE_SELECTION      33205
#define ID_PCB_TOOL_DRC                 33208
#define ID_33209                        33209
#define ID_PCB_TOOL_PLACEMENT_RECT      33212
#define ID_PCB_TOOL_PLACEMENT_OUTSIDE_BOARD 33213
#define ID_PCB_TOOL_PLACEMENT_STOP      33215
#define ID_33217                        33217
#define ID_33218                        33218
#define ID_PCB_TOOL_EXPLODE_COMPONENT   33219
#define ID_PCB_TOOL_EXPLODE_COORDINATE  33222
#define ID_PCB_TOOL_EXPLODE_DIMENSION   33223
#define ID_PCB_TOOL_EXPLODE_POLYGON     33225
#define ID_PCB_TOOL_CONVERT_PAD_TO_VIA  33226
#define ID_PCB_TOOL_CONVERT_VIA_TO_PAD  33228
#define ID_PCB_TOOL_CREATE_COMPONENT    33229
#define ID_PCB_TOOL_CREATE_POLYGON      33234
#define ID_PCB_TOOL_CREATE_REGION       33235
#define ID_PCB_TOOL_CREATE_CUTOUT       33236
#define ID_PCB_TOOL_CREATE_BOARD_CUTOUT 33237
#define ID_PCB_TOOL_UNROUTE_ALL         33238
#define ID_PCB_TOOL_UNROUTE_NET         33239
#define ID_PCB_TOOL_UNROUTE_CONNECTION  33240
#define ID_PCB_TOOL_UNROUTE_COMPONENT   33242
#define ID_PCB_TOOL_TEAR                33243
#define ID_PCB_TOOL_PERFERENCE          33245
#define ID_PCB_TOOL_LOAD_COMPONENT      33246
#define ID_PCB_TOOL_PLACEMENT_MANUAL    33247
#define ID_PCB_TOOL_MOVE_COMPONENT      33248
#define ID_33249                        33249
#define ID_33252                        33252
#define ID_33261                        33261
#define ID_PCB_TOOL_RATS_SHOW_ALL       33262
#define ID_PCB_TOOL_RATS_SHOW_NET       33263
#define ID_PCB_TOOL_RATS_SHOW_COMP      33264
#define ID_PCB_TOOL_RATS_HIDE_ALL       33265
#define ID_PCB_TOOL_RATS_HIDE_NET       33266
#define ID_PCB_TOOL_RATS_HIDE_COMP      33267
#define ID_PCB_NET_EDIT                 33269
#define ID_PCB_NET_CLEANALL             33270
#define ID_PCB_NET_CLEANONE             33271
#define ID_PCB_NET_CLEARALL             33272
#define ID_PCB_NET_SCH                  33273
#define ID_PCB_NET_FILE                 33274
#define ID_33275                        33275
#define ID_PCB_TOOL_HIGHLIGHT_LOCATION  33276
#define ID_PCB_TOOL_HIGHLIGHT_NET       33277
#define ID_PCB_TOOL_HIGHLIGHT_CLEAR     33278
#define ID_PCB_TOOL_HIGHLIGHT_PINS      33280
#define ID_PCB_EDIT_REPLACE             33281
#define ID_PCB_EDIT_REPEAT              33282
#define ID_PCB_JUMP_COMP                33284
#define ID_PCB_JUMP_TEXT                33285
#define ID_PCB_REPORT_DRC               33286
#define ID_PCB_DESIGN_RULES             33288
#define ID_PCB_TOOL_CLEAR_DRCERROR      33289
#define ID_PCB_EDIT_CUT                 33290
#define ID_PCB_EDIT_COPY                33291
#define ID_PCB_EDIT_PASTE               33292
#define ID_ROUTE_MANUAL                 33293
#define ID_FILE_PRINT_PAGE_SETUP        33294
#define ID_PCB_VIEW_FULLSCREEN          33295
#define ID_SCH_VIEW_FULLSCREEN          33296
#define ID_PCB_SPLIT_PLANE              33299
#define ID_Menu33300                    33300
#define ID_PCB_TOOL_RATS_REFRESH        33301
#define ID_33302                        33302
#define ID_PCB_EDIT_ALIGN_LEFT          33303
#define ID_PCB_EDIT_ALIGN_TOP           33304
#define ID_PCB_EDIT_ALIGN_VPLACE        33305
#define ID_PCB_EDIT_ALIGN_HPLACE        33306
#define ID_PCB_GRID_VISIBLE             33309
#define ID_PCB_GRID_ELECTRICAL          33310
#define ID_PCB_MEASURE_DISTANCE         33311
#define ID_LIB_MANAGER_A                33330

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        560
#define _APS_NEXT_COMMAND_VALUE         33331
#define _APS_NEXT_CONTROL_VALUE         1633
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
